events {}

http {
    upstream go_servers {
        server host.docker.internal:8881;
        server host.docker.internal:8882;
        server host.docker.internal:8883;
        server host.docker.internal:8884;
    }

    server {
        listen 443 ssl;
        listen [::]:443 ssl http2;

        ssl_certificate      /etc/nginx/localhost.crt;
        ssl_certificate_key  /etc/nginx/localhost.key;

        location / {
            proxy_pass http://go_servers;
            proxy_buffering off;
            proxy_cache off;
            proxy_set_header Host $host;
            proxy_set_header Connection '';
            proxy_http_version 1.1;
            chunked_transfer_encoding off;
        }
    }
}